### ISSUE TITLE
The theme style conflicts with the tool bar toolbar

### ISSUE THREAD

**Issue by syshlang** [slavamak/obsidian-neovim#1]
- normal:
![image](https://github.com/slavamak/obsidian-neovim/assets/8163995/083013ed-3781-4628-9fb3-99cce06c42fe)
- abnormal:
Style exception when using this theme.
![image](https://github.com/slavamak/obsidian-neovim/assets/8163995/2a23cb38-75eb-4c5d-b3f6-dcdc9834175a)

**Comment by slavafyi** [comment]
@syshlang good catch! I'll check, thanks

**Comment by slavafyi** [comment]
@syshlang please update your theme to new version (0.4.0). It should be fine now. Let me know

**Comment by syshlang** [comment]
@slavamak Thank you very much for your hard work, it is normal now.
